print(1,2,3,4,5,6,7,8,9)
print(1+2)
print(type(1))
print(type(9.9))
print(type(1/2))
#print(type(1/0))
num1_variable=input("ingresa un número: ")
num2_variable=input("ingresa un número: ")
print(int(num1_variable)+int(num2_variable))